using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UIProductor.Designer
{
    public class DesignerCreator
    {
        public DesignerCreator()
        {

        }

        string CreateDesignerCs(string nameSpace, string entityName)
        {
            StringBuilder cs = new StringBuilder();
            cs.Append("//------------------------------------------------------------------------------\r\n");
            cs.Append("// <auto-generated>\r\n");
            cs.Append("//     This code was generated by a tool.\r\n");
            cs.Append("//\r\n");
            cs.Append("//     Changes to this file may cause incorrect behavior and will be lost if\r\n");
            cs.Append("//     the code is regenerated. \r\n");
            cs.Append("// </auto-generated>\r\n");
            cs.Append("//------------------------------------------------------------------------------\r\n\r\n");
            cs.Append("namespace " + nameSpace + "{\r\n");
            cs.Append(" public partial class " + entityName + "Edit {\r\n");
            cs.Append("            /// <summary>\r\n");
            cs.Append("            /// Head1 control.\r\n");
            cs.Append("            /// </summary>\r\n");
            cs.Append("            /// <remarks>\r\n");
            cs.Append("            /// Auto-generated field.\r\n");
            cs.Append("            /// To modify move field declaration from designer file to code-behind file.\r\n");
            cs.Append(" protected global::System.Web.UI.HtmlControls.HtmlHead Head1;\r\n");
            cs.Append("\r\n");
            cs.Append("            /// <summary>\r\n");
            cs.Append("            /// form1 control.\r\n");
            cs.Append("            /// </summary>\r\n");
            cs.Append("            /// <remarks>\r\n");
            cs.Append("            /// Auto-generated field.\r\n");
            cs.Append("            /// To modify move field declaration from designer file to code-behind file.\r\n");
            cs.Append(" protected global::System.Web.UI.HtmlControls.HtmlForm form1;\r\n");
            cs.Append("\r\n");
            // cs.Append(_UnitEdit.DesignerCS_CreateSelect());

            cs.Append(" }\r\n");
            cs.Append("}\r\n");

            return cs.ToString();

        }
    }
}
