using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ProjectProductor.WebPages
{
    public class DesignerCS
    {
        public static string Create_DesignerCS(string nameSpace, string pageName)
        {
            StringBuilder desig = new StringBuilder();
            desig.Append("//------------------------------------------------------------------------------\r\n");
            desig.Append("// <auto-generated>\r\n");
            desig.Append("//     This code was generated by a tool.\r\n");
            desig.Append("//\r\n");
            desig.Append("//     Changes to this file may cause incorrect behavior and will be lost if\r\n");
            desig.Append("//     the code is regenerated.\r\n");
            desig.Append("// </auto-generated>\r\n");
            desig.Append("//------------------------------------------------------------------------------\r\n");
            desig.Append("\r\n");
            desig.Append("namespace " + nameSpace + "\r\n");
            desig.Append("{\r\n");
            desig.Append("\r\n");
            desig.Append("\r\n");
            desig.Append("  public partial class " + pageName + "\r\n");
            desig.Append(" {\r\n");
            desig.Append("\r\n");
            desig.Append("     /// <summary>\r\n");
            desig.Append("     /// form1 control.\r\n");
            desig.Append("    /// </summary>\r\n");
            desig.Append("     /// <remarks>\r\n");
            desig.Append("     /// Auto-generated field.\r\n");
            desig.Append("        /// To modify move field declaration from designer file to code-behind file.\r\n");
            desig.Append("       /// </remarks>\r\n");
            desig.Append("       protected global::System.Web.UI.HtmlControls.HtmlForm form1;\r\n");
            desig.Append("   }\r\n");
            desig.Append("}\r\n");

            return desig.ToString();
        }
    }
}
